--Code for project for 
DROP TABLE IF EXISTS STUDENT;

CREATE TABLE STUDENT (
    FirstName VARCHAR(255) DEFAULT NULL,
    LastName VARCHAR(255) DEFAULT NULL,
    Age INT DEFAULT NULL,
    StudentID INT NOT NULL AUTO_INCREMENT,
    PRIMARY KEY ('StudentID')
);
